baseURL: 'https://apologiesinadvance.gay'
languageCode: 'en-gb'
title: 'Apologies In Advance'
theme: 'papermod'
params:
    profileMode:
        enabled: true
        buttons:
            - name: Wiki
              url: "https://wiki.emfcamp.org/wiki/Village:AIA"
            - name: Contact Us
              url: "https://apologiesinadvance.gay/contact-us/index.html"
